[pytest]
filterwarnings =
    ignore:The set_bad function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_over function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_under function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:'l1_ratios=None' was deprecated in version 1.8 and will trigger an error in 1.10.*:FutureWarning:sklearn\.linear_model\._logistic
    ignore:Using `httpx` with `starlette\.testclient` is deprecated.*
    ignore:(?s).*on_event is deprecated.*:DeprecationWarning
    ignore:'asyncio\.iscoroutinefunction' is deprecated.*
    ignore:LightGBM binary classifier with TreeExplainer shap values output has changed.*:UserWarning:shap\.explainers\._tree


