[pytest]
filterwarnings =
    ignore:The set_bad function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_over function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_under function will be deprecated in a future version.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
